apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "ip-echo-chart.labels" . | nindent 4 }}
    {{- include "ip-echo-chart.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "ip-echo-chart.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ip-echo-chart.backendLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: ip-echo-api-service
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          startupProbe:
            httpGet:
              path: {{ .Values.backend.probes.startup.path }}
              port: {{ .Values.backend.containerPort }}
            failureThreshold: {{ .Values.backend.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.backend.probes.startup.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.backend.probes.readiness.successThreshold }}

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
